# Generated by Django 5.0.3 on 2024-03-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprendiz',
            old_name='FECHA_VOID_HASH',
            new_name='HASH_SEND',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='FECHA_VOID_HASH',
            new_name='HASH_SEND',
        ),
    ]
